require('prototypes.basic-items')
require('prototypes.circuits')
require('prototypes.dyes')
require('prototypes.military')
require('prototypes.miscellaneous')
require('prototypes.recipe-changes')
require('prototypes.rocket-parts')

require('technology')
require('item-groups')
require('util')